import type { Metadata } from "next";
import HeaderComponent from "@/components/HeaderComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <HeaderComponent />
      { children }
    </main>
  );
}
